spring.data.mongodb.database: aeropath

auth:
  jwt:
    secret: top-secret-for-token

oauth:
  github:
    client:
      id: Iv1.5850456df7dc4fd8
      secret: 141a3c74f160cdae4343ce10c9e545e1d8f1205d
    redirecturl: http://localhost:3000/oauth/github