spring.data.mongodb.database: aeropath

auth:
  jwt:
    secret: top-ultra-secret-for-token

oauth:
  github:
    client:
      id: Iv1.5850456df7dc4fd8
      secret: xxxxxx
    redirecturl: http://localhost:3000/oauth/github

google:
  apikey: xxx

openweather:
  apikey: xxxxx